### ISSUE TITLE
User's Changing Names and DQ Query Conflicts

### ISSUE THREAD

**Issue by andrewld3** [CSC480-18S/Blue-Team#178]
DB Integration will be impossible if we allow a user to change their name at all. Based upon the current Query call, the parameters are as followed: Username, Score. Database currently only accepts the first username ever entered and all subsequent logon's default to that name in dB land. Thus, if a user logs in for a second time, and uses a different username, his or her stats WILL NOT update. We need to address this...uh now.

**Comment by andrewld3** [comment]
updatePlayerCumulative( ) is affected.

**Comment by andrewld3** [comment]
updatePlayerBonusCount( ) is affected

**Comment by kpemblet** [comment]
There is a discussion in DB chat but determination for this is:

GUI has already made the popups that can be displayed. They just need the logic code behind it so that if username is found linekd to mac address the login popup with only the team switch is displayed. Otherwise the popup with creating a username is displayed.

**Comment by bohdan91** [comment]
So first username you choose - stays with you forever ? 
That's sad...

**Comment by andrewld3** [comment]
DB Calls are fixed. Currently implementing name-change. Marking this issue as closed.
